- hosts: all
  become: yes
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Copiar página web
      copy:
        src: ./index.html
        dest: /var/www/html/index.html

    - name: Asegurar que Apache está corriendo
      service:
        name: apache2
        state: started
        enabled: yes


